# Generated by Django 4.0.5 on 2022-06-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_date_created_comment_date_published_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganizationMembers',
            new_name='OrganizationMember',
        ),
        migrations.RenameModel(
            old_name='ProjectMembers',
            new_name='ProjectMember',
        ),
    ]
