# Generated by Django 4.0.5 on 2022-06-26 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_organizationmembers_organizationmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='language',
            field=models.IntegerField(blank=True, choices=[('FR', 'French'), ('EN', 'English'), ('ES', 'Spanish'), ('DE', 'German'), ('OT', 'Other')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Member')], default=2, max_length=1),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('M', 'Member')], default='M', max_length=1),
        ),
    ]
