# Generated by Django 4.0.5 on 2022-06-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_organization_language_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isParent',
            field=models.BooleanField(default=False),
        ),
    ]
