# Generated by Django 4.0.5 on 2022-06-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_isparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='language',
            field=models.CharField(blank=True, choices=[('FR', 'French'), ('EN', 'English'), ('ES', 'Spanish'), ('DE', 'German'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, default='EN', max_length=200),
        ),
    ]
